services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: challenge_frontend
    network_mode: "host"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: challenge_auth-service
    network_mode: "host"
    volumes:
      - ./auth-service:/app
    environment:
      - PYTHONUNBUFFERED=1
