services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: challenge_frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    environment:
      - PYTHONUNBUFFERED=1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: challenge_auth-service
    ports:
      - "5050:5050"
    volumes:
      - ./auth-service:/app
    environment:
      - PYTHONUNBUFFERED=1
